version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./data:/app/data  # Presuming you want to store your SQLite DB here
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/sql_app.db